# -*- Makefile -*- 
.POSIX:
CDEFS=-DUM_VERBOSE -DUM_MPOOL
COPT=-O3 -g -fno-delete-null-pointer-checks -fstrict-aliasing `sh oscflags.sh`
CWARN=-Wall -W

CDBG=
CFLAGS=$(COPT) $(CWARN) $(CDBG) $(CDEFS) $(XCF)

OBJS=rt.o util.o crt.o co.o main.o mpool.o vers.o
umx: $(OBJS)
	$(CC) $(CFLAGS) $(LFLAGS) $(OBJS) `sh oslflags.sh` -o umx

clean:
	-rm -f umx $(OBJS)

force: clean
	$(MAKE) umx

CS=$(OBJS:.o=.c)
Makefile: Makefile.tmpl $(CS)
	cat Makefile.tmpl > $@
	$(MAKE) -f Makefile.tmpl _depend
_depend:
	@gcc -MM $(CDEFS) $(CS) >> Makefile
###END###
